// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8yQDwznrz2gAukfn_ZN93H_-NOsepCAw',
    appId: '1:886698111727:web:02a96e55f94966db4e611a',
    messagingSenderId: '886698111727',
    projectId: 'flutter-chat-app-fde3a',
    authDomain: 'flutter-chat-app-fde3a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fde3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV7tBFuSII-REiHF8vK3RMiUD2bFQunfM',
    appId: '1:886698111727:android:e5644a68ff1d06234e611a',
    messagingSenderId: '886698111727',
    projectId: 'flutter-chat-app-fde3a',
    storageBucket: 'flutter-chat-app-fde3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFL9WKSF7936IgwJzmHs7wBRLJtSCKHAI',
    appId: '1:886698111727:ios:6de67f5df85b38cf4e611a',
    messagingSenderId: '886698111727',
    projectId: 'flutter-chat-app-fde3a',
    storageBucket: 'flutter-chat-app-fde3a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFL9WKSF7936IgwJzmHs7wBRLJtSCKHAI',
    appId: '1:886698111727:ios:269d7335fa2dd2f24e611a',
    messagingSenderId: '886698111727',
    projectId: 'flutter-chat-app-fde3a',
    storageBucket: 'flutter-chat-app-fde3a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8yQDwznrz2gAukfn_ZN93H_-NOsepCAw',
    appId: '1:886698111727:web:9d7ec0431948adfc4e611a',
    messagingSenderId: '886698111727',
    projectId: 'flutter-chat-app-fde3a',
    authDomain: 'flutter-chat-app-fde3a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fde3a.firebasestorage.app',
  );

}